name: SonarHearing
version: 4.3
author: Asynchronous
description: This plugin allows you to detect entities around you when sneaking. More informations with /sonarhearing command.
website: http://roytreo28.ddns.net/asynchronous
main: fr.roytreo.sonarhearing.core.SonarHearingPlugin
depend: [GlowAPI]
soft-depend: [PacketListenerApi]
commands:
  sonarhearing:
    aliases: [sh]
    description: Main command of the Sonar Hearing plugin.