##################################################################
#                                                                #
#  #####   #######   ###   ##  ########  ##########   #########  #
# ###     ###   ###  ####  ##  ########      ###     ###     ### #
# ##      ##     ##  # ### ##  ##            ##      ##          #
# ##      ##     ##  #  ## ##  #####         ##      ##   #####  #
# ##      ##     ##  ##  ####  #####         ##      ##   #  ##  #
# ###     ###   ###  ##   ###  ##           ###      ###    ###  #
#  #####   #######   ##    ##  ##        ##########   ########   #
#                                                                #
##################################################################
#Here you can configure some aspects of the plugin.
#Effects: active or not some effects when activing your ability
effects:
  red-alert: true
  heartbeat: true
#Tamed mob: if "force-color" is true, tamed mobs will be seen as the color 
#specified in "color".
tamed-mob:
  force-color: true
  color: BLUE
#This is the delay before activate the hearing ability (in seconds)
delay: 0
#Freeze players when using the sonar ? true or false.
freeze: false