name: SonarHearing
version: 4.3
author: Royalpha
description: This plugin allows you to detect entities around you when sneaking. More informations with /sonarhearing command.
main: fr.royalpha.sonarhearing.core.SonarHearingPlugin
depend: [GlowAPI, PacketListenerApi]
commands:
  sonarhearing:
    aliases: [sh]
    description: Main command of the Sonar Hearing plugin.